
# Site settings
title: Jessica's Blog
description: A starter site
baseurl: /Blog 
url: "http://ciprianoj.github.io" 

markdown: kramdown

defaults:  
  # template for pages unless an alternative is specified
  - scope:
      path: ""
    values:
      layout: "default"
